vich_uploader:
    db_driver: orm

    mappings:
        profile_image:
            uri_prefix: /images/users/icon
            upload_destination: '%kernel.project_dir%/public/images/users/icon'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
